spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Enable Flyway migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
websiteURL: https://mystore.com